# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5711cbbeabaa9a0ee60b4276516d6e70a72b1d9809601125b3fef4fb8fda1dfc85245b66992f2467220e852974e5a5115d51bea6502a98881aac98ef60f2d46a

test:
  secret_key_base: b332c9235b427e13dd7e1b08a0bcc294fbb18986909fbe70c07b30a72826a878016b22da1204a1841123ceb73c87e1b12dfabac4f04b3b7b0032ad04b5a5f911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
